# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=264)),
                ('plazas', models.CharField(max_length=264)),
                ('aire_acondicionado', models.CharField(max_length=264)),
                ('tipo_transmision', models.CharField(max_length=264)),
                ('lugar_recodiga', models.CharField(max_length=264)),
                ('precio', models.FloatField()),
                ('jornada', models.IntegerField(max_length=264)),
                ('is_alquiled', models.BooleanField()),
            ],
        ),
    ]
