# Generated by Django 2.0b1 on 2017-10-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0002_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='jornada',
            field=models.IntegerField(),
        ),
    ]
