# Generated by Django 2.0b1 on 2017-10-30 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0003_auto_20171030_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('V', 'Viudo'), ('D', 'Divorciado')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='estrellas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='inicio_app',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='total_viajes',
            field=models.IntegerField(default=0),
        ),
    ]
