# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conductor', '0004_auto_20171030_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='id',
        ),
        migrations.AddField(
            model_name='conductor',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
