# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0006_auto_20171112_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
