# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0007_auto_20171112_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='user',
            new_name='user_id',
        ),
    ]
