# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conductor', '0010_auto_20171113_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
