# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0011_auto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='user',
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
