# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0012_auto_20171113_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='correo',
        ),
    ]
