# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0015_auto_20171120_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user_receiver',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user_sender',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
