# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=264)),
                ('plazas', models.CharField(max_length=264)),
                ('aire_acondicionado', models.CharField(max_length=264)),
                ('tipo_transmision', models.CharField(max_length=264)),
                ('lugar_recodiga', models.CharField(max_length=264)),
                ('precio', models.FloatField()),
                ('jornada', models.IntegerField()),
                ('is_alquiled', models.BooleanField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
