# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto', '0002_auto_20171113_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_status', models.CharField(choices=[('1', 'espera'), ('2', 'aceptado'), ('3', 'finalizado')], default=('1', 'espera'), max_length=1)),
                ('User_alquila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_alquila', to=settings.AUTH_USER_MODEL)),
                ('User_contrata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contrata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
