# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto', '0005_contrato_auto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together=set([('User_alquila', 'User_contrata', 'auto')]),
        ),
    ]
