# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_auto_20171120_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='hired_status',
            field=models.CharField(choices=[('1', 'espera'), ('2', 'aceptado'), ('3', 'finalizado')], default='1', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together=set([]),
        ),
    ]
