# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='is_alquiled',
            field=models.BooleanField(default=False),
        ),
    ]
